################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/ti/examples/OPUS/opus-1.1.2/silk/A2NLSF.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/CNG.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/HP_variable_cutoff.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/LPC_analysis_filter.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/LPC_inv_pred_gain.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/LP_variable_cutoff.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF2A.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_VQ.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_VQ_weights_laroia.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_decode.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_del_dec_quant.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_encode.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_stabilize.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_unpack.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NSQ.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/NSQ_del_dec.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/PLC.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/VAD.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/VQ_WMat_EC.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/ana_filt_bank_1.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/biquad_alt.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/bwexpander.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/bwexpander_32.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/check_control_input.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/code_signs.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/control_SNR.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/control_audio_bandwidth.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/control_codec.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/debug.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/dec_API.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decode_core.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decode_frame.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decode_indices.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decode_parameters.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decode_pitch.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decode_pulses.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/decoder_set_fs.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/enc_API.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/encode_indices.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/encode_pulses.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/gain_quant.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/init_decoder.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/init_encoder.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/inner_prod_aligned.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/interpolate.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/lin2log.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/log2lin.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/pitch_est_tables.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/process_NLSFs.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/quant_LTP_gains.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_down2.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_down2_3.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_AR2.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_IIR_FIR.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_down_FIR.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_up2_HQ.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_rom.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/shell_coder.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/sigm_Q15.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/sort.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_LR_to_MS.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_MS_to_LR.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_decode_pred.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_encode_pred.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_find_predictor.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_quant_pred.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/sum_sqr_shift.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/table_LSF_cos.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_LTP.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_NLSF_CB_NB_MB.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_NLSF_CB_WB.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_gain.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_other.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_pitch_lag.c \
D:/ti/examples/OPUS/opus-1.1.2/silk/tables_pulses_per_block.c 

OBJS += \
./opus-1.1.2/silk/A2NLSF.obj \
./opus-1.1.2/silk/CNG.obj \
./opus-1.1.2/silk/HP_variable_cutoff.obj \
./opus-1.1.2/silk/LPC_analysis_filter.obj \
./opus-1.1.2/silk/LPC_inv_pred_gain.obj \
./opus-1.1.2/silk/LP_variable_cutoff.obj \
./opus-1.1.2/silk/NLSF2A.obj \
./opus-1.1.2/silk/NLSF_VQ.obj \
./opus-1.1.2/silk/NLSF_VQ_weights_laroia.obj \
./opus-1.1.2/silk/NLSF_decode.obj \
./opus-1.1.2/silk/NLSF_del_dec_quant.obj \
./opus-1.1.2/silk/NLSF_encode.obj \
./opus-1.1.2/silk/NLSF_stabilize.obj \
./opus-1.1.2/silk/NLSF_unpack.obj \
./opus-1.1.2/silk/NSQ.obj \
./opus-1.1.2/silk/NSQ_del_dec.obj \
./opus-1.1.2/silk/PLC.obj \
./opus-1.1.2/silk/VAD.obj \
./opus-1.1.2/silk/VQ_WMat_EC.obj \
./opus-1.1.2/silk/ana_filt_bank_1.obj \
./opus-1.1.2/silk/biquad_alt.obj \
./opus-1.1.2/silk/bwexpander.obj \
./opus-1.1.2/silk/bwexpander_32.obj \
./opus-1.1.2/silk/check_control_input.obj \
./opus-1.1.2/silk/code_signs.obj \
./opus-1.1.2/silk/control_SNR.obj \
./opus-1.1.2/silk/control_audio_bandwidth.obj \
./opus-1.1.2/silk/control_codec.obj \
./opus-1.1.2/silk/debug.obj \
./opus-1.1.2/silk/dec_API.obj \
./opus-1.1.2/silk/decode_core.obj \
./opus-1.1.2/silk/decode_frame.obj \
./opus-1.1.2/silk/decode_indices.obj \
./opus-1.1.2/silk/decode_parameters.obj \
./opus-1.1.2/silk/decode_pitch.obj \
./opus-1.1.2/silk/decode_pulses.obj \
./opus-1.1.2/silk/decoder_set_fs.obj \
./opus-1.1.2/silk/enc_API.obj \
./opus-1.1.2/silk/encode_indices.obj \
./opus-1.1.2/silk/encode_pulses.obj \
./opus-1.1.2/silk/gain_quant.obj \
./opus-1.1.2/silk/init_decoder.obj \
./opus-1.1.2/silk/init_encoder.obj \
./opus-1.1.2/silk/inner_prod_aligned.obj \
./opus-1.1.2/silk/interpolate.obj \
./opus-1.1.2/silk/lin2log.obj \
./opus-1.1.2/silk/log2lin.obj \
./opus-1.1.2/silk/pitch_est_tables.obj \
./opus-1.1.2/silk/process_NLSFs.obj \
./opus-1.1.2/silk/quant_LTP_gains.obj \
./opus-1.1.2/silk/resampler.obj \
./opus-1.1.2/silk/resampler_down2.obj \
./opus-1.1.2/silk/resampler_down2_3.obj \
./opus-1.1.2/silk/resampler_private_AR2.obj \
./opus-1.1.2/silk/resampler_private_IIR_FIR.obj \
./opus-1.1.2/silk/resampler_private_down_FIR.obj \
./opus-1.1.2/silk/resampler_private_up2_HQ.obj \
./opus-1.1.2/silk/resampler_rom.obj \
./opus-1.1.2/silk/shell_coder.obj \
./opus-1.1.2/silk/sigm_Q15.obj \
./opus-1.1.2/silk/sort.obj \
./opus-1.1.2/silk/stereo_LR_to_MS.obj \
./opus-1.1.2/silk/stereo_MS_to_LR.obj \
./opus-1.1.2/silk/stereo_decode_pred.obj \
./opus-1.1.2/silk/stereo_encode_pred.obj \
./opus-1.1.2/silk/stereo_find_predictor.obj \
./opus-1.1.2/silk/stereo_quant_pred.obj \
./opus-1.1.2/silk/sum_sqr_shift.obj \
./opus-1.1.2/silk/table_LSF_cos.obj \
./opus-1.1.2/silk/tables_LTP.obj \
./opus-1.1.2/silk/tables_NLSF_CB_NB_MB.obj \
./opus-1.1.2/silk/tables_NLSF_CB_WB.obj \
./opus-1.1.2/silk/tables_gain.obj \
./opus-1.1.2/silk/tables_other.obj \
./opus-1.1.2/silk/tables_pitch_lag.obj \
./opus-1.1.2/silk/tables_pulses_per_block.obj 

C_DEPS += \
./opus-1.1.2/silk/A2NLSF.pp \
./opus-1.1.2/silk/CNG.pp \
./opus-1.1.2/silk/HP_variable_cutoff.pp \
./opus-1.1.2/silk/LPC_analysis_filter.pp \
./opus-1.1.2/silk/LPC_inv_pred_gain.pp \
./opus-1.1.2/silk/LP_variable_cutoff.pp \
./opus-1.1.2/silk/NLSF2A.pp \
./opus-1.1.2/silk/NLSF_VQ.pp \
./opus-1.1.2/silk/NLSF_VQ_weights_laroia.pp \
./opus-1.1.2/silk/NLSF_decode.pp \
./opus-1.1.2/silk/NLSF_del_dec_quant.pp \
./opus-1.1.2/silk/NLSF_encode.pp \
./opus-1.1.2/silk/NLSF_stabilize.pp \
./opus-1.1.2/silk/NLSF_unpack.pp \
./opus-1.1.2/silk/NSQ.pp \
./opus-1.1.2/silk/NSQ_del_dec.pp \
./opus-1.1.2/silk/PLC.pp \
./opus-1.1.2/silk/VAD.pp \
./opus-1.1.2/silk/VQ_WMat_EC.pp \
./opus-1.1.2/silk/ana_filt_bank_1.pp \
./opus-1.1.2/silk/biquad_alt.pp \
./opus-1.1.2/silk/bwexpander.pp \
./opus-1.1.2/silk/bwexpander_32.pp \
./opus-1.1.2/silk/check_control_input.pp \
./opus-1.1.2/silk/code_signs.pp \
./opus-1.1.2/silk/control_SNR.pp \
./opus-1.1.2/silk/control_audio_bandwidth.pp \
./opus-1.1.2/silk/control_codec.pp \
./opus-1.1.2/silk/debug.pp \
./opus-1.1.2/silk/dec_API.pp \
./opus-1.1.2/silk/decode_core.pp \
./opus-1.1.2/silk/decode_frame.pp \
./opus-1.1.2/silk/decode_indices.pp \
./opus-1.1.2/silk/decode_parameters.pp \
./opus-1.1.2/silk/decode_pitch.pp \
./opus-1.1.2/silk/decode_pulses.pp \
./opus-1.1.2/silk/decoder_set_fs.pp \
./opus-1.1.2/silk/enc_API.pp \
./opus-1.1.2/silk/encode_indices.pp \
./opus-1.1.2/silk/encode_pulses.pp \
./opus-1.1.2/silk/gain_quant.pp \
./opus-1.1.2/silk/init_decoder.pp \
./opus-1.1.2/silk/init_encoder.pp \
./opus-1.1.2/silk/inner_prod_aligned.pp \
./opus-1.1.2/silk/interpolate.pp \
./opus-1.1.2/silk/lin2log.pp \
./opus-1.1.2/silk/log2lin.pp \
./opus-1.1.2/silk/pitch_est_tables.pp \
./opus-1.1.2/silk/process_NLSFs.pp \
./opus-1.1.2/silk/quant_LTP_gains.pp \
./opus-1.1.2/silk/resampler.pp \
./opus-1.1.2/silk/resampler_down2.pp \
./opus-1.1.2/silk/resampler_down2_3.pp \
./opus-1.1.2/silk/resampler_private_AR2.pp \
./opus-1.1.2/silk/resampler_private_IIR_FIR.pp \
./opus-1.1.2/silk/resampler_private_down_FIR.pp \
./opus-1.1.2/silk/resampler_private_up2_HQ.pp \
./opus-1.1.2/silk/resampler_rom.pp \
./opus-1.1.2/silk/shell_coder.pp \
./opus-1.1.2/silk/sigm_Q15.pp \
./opus-1.1.2/silk/sort.pp \
./opus-1.1.2/silk/stereo_LR_to_MS.pp \
./opus-1.1.2/silk/stereo_MS_to_LR.pp \
./opus-1.1.2/silk/stereo_decode_pred.pp \
./opus-1.1.2/silk/stereo_encode_pred.pp \
./opus-1.1.2/silk/stereo_find_predictor.pp \
./opus-1.1.2/silk/stereo_quant_pred.pp \
./opus-1.1.2/silk/sum_sqr_shift.pp \
./opus-1.1.2/silk/table_LSF_cos.pp \
./opus-1.1.2/silk/tables_LTP.pp \
./opus-1.1.2/silk/tables_NLSF_CB_NB_MB.pp \
./opus-1.1.2/silk/tables_NLSF_CB_WB.pp \
./opus-1.1.2/silk/tables_gain.pp \
./opus-1.1.2/silk/tables_other.pp \
./opus-1.1.2/silk/tables_pitch_lag.pp \
./opus-1.1.2/silk/tables_pulses_per_block.pp 

C_DEPS__QUOTED += \
"opus-1.1.2\silk\A2NLSF.pp" \
"opus-1.1.2\silk\CNG.pp" \
"opus-1.1.2\silk\HP_variable_cutoff.pp" \
"opus-1.1.2\silk\LPC_analysis_filter.pp" \
"opus-1.1.2\silk\LPC_inv_pred_gain.pp" \
"opus-1.1.2\silk\LP_variable_cutoff.pp" \
"opus-1.1.2\silk\NLSF2A.pp" \
"opus-1.1.2\silk\NLSF_VQ.pp" \
"opus-1.1.2\silk\NLSF_VQ_weights_laroia.pp" \
"opus-1.1.2\silk\NLSF_decode.pp" \
"opus-1.1.2\silk\NLSF_del_dec_quant.pp" \
"opus-1.1.2\silk\NLSF_encode.pp" \
"opus-1.1.2\silk\NLSF_stabilize.pp" \
"opus-1.1.2\silk\NLSF_unpack.pp" \
"opus-1.1.2\silk\NSQ.pp" \
"opus-1.1.2\silk\NSQ_del_dec.pp" \
"opus-1.1.2\silk\PLC.pp" \
"opus-1.1.2\silk\VAD.pp" \
"opus-1.1.2\silk\VQ_WMat_EC.pp" \
"opus-1.1.2\silk\ana_filt_bank_1.pp" \
"opus-1.1.2\silk\biquad_alt.pp" \
"opus-1.1.2\silk\bwexpander.pp" \
"opus-1.1.2\silk\bwexpander_32.pp" \
"opus-1.1.2\silk\check_control_input.pp" \
"opus-1.1.2\silk\code_signs.pp" \
"opus-1.1.2\silk\control_SNR.pp" \
"opus-1.1.2\silk\control_audio_bandwidth.pp" \
"opus-1.1.2\silk\control_codec.pp" \
"opus-1.1.2\silk\debug.pp" \
"opus-1.1.2\silk\dec_API.pp" \
"opus-1.1.2\silk\decode_core.pp" \
"opus-1.1.2\silk\decode_frame.pp" \
"opus-1.1.2\silk\decode_indices.pp" \
"opus-1.1.2\silk\decode_parameters.pp" \
"opus-1.1.2\silk\decode_pitch.pp" \
"opus-1.1.2\silk\decode_pulses.pp" \
"opus-1.1.2\silk\decoder_set_fs.pp" \
"opus-1.1.2\silk\enc_API.pp" \
"opus-1.1.2\silk\encode_indices.pp" \
"opus-1.1.2\silk\encode_pulses.pp" \
"opus-1.1.2\silk\gain_quant.pp" \
"opus-1.1.2\silk\init_decoder.pp" \
"opus-1.1.2\silk\init_encoder.pp" \
"opus-1.1.2\silk\inner_prod_aligned.pp" \
"opus-1.1.2\silk\interpolate.pp" \
"opus-1.1.2\silk\lin2log.pp" \
"opus-1.1.2\silk\log2lin.pp" \
"opus-1.1.2\silk\pitch_est_tables.pp" \
"opus-1.1.2\silk\process_NLSFs.pp" \
"opus-1.1.2\silk\quant_LTP_gains.pp" \
"opus-1.1.2\silk\resampler.pp" \
"opus-1.1.2\silk\resampler_down2.pp" \
"opus-1.1.2\silk\resampler_down2_3.pp" \
"opus-1.1.2\silk\resampler_private_AR2.pp" \
"opus-1.1.2\silk\resampler_private_IIR_FIR.pp" \
"opus-1.1.2\silk\resampler_private_down_FIR.pp" \
"opus-1.1.2\silk\resampler_private_up2_HQ.pp" \
"opus-1.1.2\silk\resampler_rom.pp" \
"opus-1.1.2\silk\shell_coder.pp" \
"opus-1.1.2\silk\sigm_Q15.pp" \
"opus-1.1.2\silk\sort.pp" \
"opus-1.1.2\silk\stereo_LR_to_MS.pp" \
"opus-1.1.2\silk\stereo_MS_to_LR.pp" \
"opus-1.1.2\silk\stereo_decode_pred.pp" \
"opus-1.1.2\silk\stereo_encode_pred.pp" \
"opus-1.1.2\silk\stereo_find_predictor.pp" \
"opus-1.1.2\silk\stereo_quant_pred.pp" \
"opus-1.1.2\silk\sum_sqr_shift.pp" \
"opus-1.1.2\silk\table_LSF_cos.pp" \
"opus-1.1.2\silk\tables_LTP.pp" \
"opus-1.1.2\silk\tables_NLSF_CB_NB_MB.pp" \
"opus-1.1.2\silk\tables_NLSF_CB_WB.pp" \
"opus-1.1.2\silk\tables_gain.pp" \
"opus-1.1.2\silk\tables_other.pp" \
"opus-1.1.2\silk\tables_pitch_lag.pp" \
"opus-1.1.2\silk\tables_pulses_per_block.pp" 

OBJS__QUOTED += \
"opus-1.1.2\silk\A2NLSF.obj" \
"opus-1.1.2\silk\CNG.obj" \
"opus-1.1.2\silk\HP_variable_cutoff.obj" \
"opus-1.1.2\silk\LPC_analysis_filter.obj" \
"opus-1.1.2\silk\LPC_inv_pred_gain.obj" \
"opus-1.1.2\silk\LP_variable_cutoff.obj" \
"opus-1.1.2\silk\NLSF2A.obj" \
"opus-1.1.2\silk\NLSF_VQ.obj" \
"opus-1.1.2\silk\NLSF_VQ_weights_laroia.obj" \
"opus-1.1.2\silk\NLSF_decode.obj" \
"opus-1.1.2\silk\NLSF_del_dec_quant.obj" \
"opus-1.1.2\silk\NLSF_encode.obj" \
"opus-1.1.2\silk\NLSF_stabilize.obj" \
"opus-1.1.2\silk\NLSF_unpack.obj" \
"opus-1.1.2\silk\NSQ.obj" \
"opus-1.1.2\silk\NSQ_del_dec.obj" \
"opus-1.1.2\silk\PLC.obj" \
"opus-1.1.2\silk\VAD.obj" \
"opus-1.1.2\silk\VQ_WMat_EC.obj" \
"opus-1.1.2\silk\ana_filt_bank_1.obj" \
"opus-1.1.2\silk\biquad_alt.obj" \
"opus-1.1.2\silk\bwexpander.obj" \
"opus-1.1.2\silk\bwexpander_32.obj" \
"opus-1.1.2\silk\check_control_input.obj" \
"opus-1.1.2\silk\code_signs.obj" \
"opus-1.1.2\silk\control_SNR.obj" \
"opus-1.1.2\silk\control_audio_bandwidth.obj" \
"opus-1.1.2\silk\control_codec.obj" \
"opus-1.1.2\silk\debug.obj" \
"opus-1.1.2\silk\dec_API.obj" \
"opus-1.1.2\silk\decode_core.obj" \
"opus-1.1.2\silk\decode_frame.obj" \
"opus-1.1.2\silk\decode_indices.obj" \
"opus-1.1.2\silk\decode_parameters.obj" \
"opus-1.1.2\silk\decode_pitch.obj" \
"opus-1.1.2\silk\decode_pulses.obj" \
"opus-1.1.2\silk\decoder_set_fs.obj" \
"opus-1.1.2\silk\enc_API.obj" \
"opus-1.1.2\silk\encode_indices.obj" \
"opus-1.1.2\silk\encode_pulses.obj" \
"opus-1.1.2\silk\gain_quant.obj" \
"opus-1.1.2\silk\init_decoder.obj" \
"opus-1.1.2\silk\init_encoder.obj" \
"opus-1.1.2\silk\inner_prod_aligned.obj" \
"opus-1.1.2\silk\interpolate.obj" \
"opus-1.1.2\silk\lin2log.obj" \
"opus-1.1.2\silk\log2lin.obj" \
"opus-1.1.2\silk\pitch_est_tables.obj" \
"opus-1.1.2\silk\process_NLSFs.obj" \
"opus-1.1.2\silk\quant_LTP_gains.obj" \
"opus-1.1.2\silk\resampler.obj" \
"opus-1.1.2\silk\resampler_down2.obj" \
"opus-1.1.2\silk\resampler_down2_3.obj" \
"opus-1.1.2\silk\resampler_private_AR2.obj" \
"opus-1.1.2\silk\resampler_private_IIR_FIR.obj" \
"opus-1.1.2\silk\resampler_private_down_FIR.obj" \
"opus-1.1.2\silk\resampler_private_up2_HQ.obj" \
"opus-1.1.2\silk\resampler_rom.obj" \
"opus-1.1.2\silk\shell_coder.obj" \
"opus-1.1.2\silk\sigm_Q15.obj" \
"opus-1.1.2\silk\sort.obj" \
"opus-1.1.2\silk\stereo_LR_to_MS.obj" \
"opus-1.1.2\silk\stereo_MS_to_LR.obj" \
"opus-1.1.2\silk\stereo_decode_pred.obj" \
"opus-1.1.2\silk\stereo_encode_pred.obj" \
"opus-1.1.2\silk\stereo_find_predictor.obj" \
"opus-1.1.2\silk\stereo_quant_pred.obj" \
"opus-1.1.2\silk\sum_sqr_shift.obj" \
"opus-1.1.2\silk\table_LSF_cos.obj" \
"opus-1.1.2\silk\tables_LTP.obj" \
"opus-1.1.2\silk\tables_NLSF_CB_NB_MB.obj" \
"opus-1.1.2\silk\tables_NLSF_CB_WB.obj" \
"opus-1.1.2\silk\tables_gain.obj" \
"opus-1.1.2\silk\tables_other.obj" \
"opus-1.1.2\silk\tables_pitch_lag.obj" \
"opus-1.1.2\silk\tables_pulses_per_block.obj" 

C_SRCS__QUOTED += \
"D:/ti/examples/OPUS/opus-1.1.2/silk/A2NLSF.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/CNG.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/HP_variable_cutoff.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/LPC_analysis_filter.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/LPC_inv_pred_gain.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/LP_variable_cutoff.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF2A.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_VQ.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_VQ_weights_laroia.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_decode.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_del_dec_quant.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_encode.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_stabilize.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NLSF_unpack.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NSQ.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/NSQ_del_dec.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/PLC.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/VAD.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/VQ_WMat_EC.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/ana_filt_bank_1.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/biquad_alt.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/bwexpander.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/bwexpander_32.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/check_control_input.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/code_signs.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/control_SNR.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/control_audio_bandwidth.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/control_codec.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/debug.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/dec_API.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decode_core.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decode_frame.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decode_indices.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decode_parameters.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decode_pitch.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decode_pulses.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/decoder_set_fs.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/enc_API.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/encode_indices.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/encode_pulses.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/gain_quant.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/init_decoder.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/init_encoder.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/inner_prod_aligned.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/interpolate.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/lin2log.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/log2lin.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/pitch_est_tables.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/process_NLSFs.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/quant_LTP_gains.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_down2.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_down2_3.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_AR2.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_IIR_FIR.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_down_FIR.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_private_up2_HQ.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/resampler_rom.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/shell_coder.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/sigm_Q15.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/sort.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_LR_to_MS.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_MS_to_LR.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_decode_pred.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_encode_pred.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_find_predictor.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/stereo_quant_pred.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/sum_sqr_shift.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/table_LSF_cos.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_LTP.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_NLSF_CB_NB_MB.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_NLSF_CB_WB.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_gain.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_other.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_pitch_lag.c" \
"D:/ti/examples/OPUS/opus-1.1.2/silk/tables_pulses_per_block.c" 


