/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#include "central.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CentralInformation_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, CentralInformation, name, name, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, CentralInformation, platform, name, 0),
    PB_LAST_FIELD
};

const pb_field_t GetCentralInformation_fields[1] = {
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
