/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#include "device.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeviceBattery_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, DeviceBattery, level, level, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, DeviceBattery, scale, level, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, DeviceBattery, status, scale, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceStatus_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, DeviceStatus, link, link, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, DeviceStatus, nfmi, link, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, DeviceStatus, presence, nfmi, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceInformation_fields[9] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, DeviceInformation, serial_number, serial_number, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, DeviceInformation, name, serial_number, 0),
    PB_FIELD(  3, UENUM   , REPEATED, STATIC  , OTHER, DeviceInformation, supported_transports, name, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, DeviceInformation, device_type, supported_transports, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, DeviceInformation, device_id, device_type, 0),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, DeviceInformation, battery, device_id, &DeviceBattery_fields),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, DeviceInformation, status, battery, &DeviceStatus_fields),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, DeviceInformation, product_color, status, 0),
    PB_LAST_FIELD
};

const pb_field_t GetDeviceInformation_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, GetDeviceInformation, device_id, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceConfiguration_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, DeviceConfiguration, needs_assistant_override, needs_assistant_override, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, DeviceConfiguration, needs_setup, needs_assistant_override, 0),
    PB_LAST_FIELD
};

const pb_field_t GetDeviceConfiguration_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t OverrideAssistant_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, OverrideAssistant, error_code, error_code, 0),
    PB_LAST_FIELD
};

const pb_field_t StartSetup_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t CompleteSetup_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, CompleteSetup, error_code, error_code, 0),
    PB_LAST_FIELD
};

const pb_field_t NotifyDeviceConfiguration_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, NotifyDeviceConfiguration, device_configuration, device_configuration, &DeviceConfiguration_fields),
    PB_LAST_FIELD
};

const pb_field_t UpdateDeviceInformation_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, UpdateDeviceInformation, name, name, 0),
    PB_LAST_FIELD
};

const pb_field_t NotifyDeviceInformation_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, NotifyDeviceInformation, device_information, device_information, &DeviceInformation_fields),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceInformation, battery) < 65536 && pb_membersize(DeviceInformation, status) < 65536 && pb_membersize(NotifyDeviceConfiguration, device_configuration) < 65536 && pb_membersize(NotifyDeviceInformation, device_information) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_DeviceBattery_DeviceStatus_DeviceInformation_GetDeviceInformation_DeviceConfiguration_GetDeviceConfiguration_OverrideAssistant_StartSetup_CompleteSetup_NotifyDeviceConfiguration_UpdateDeviceInformation_NotifyDeviceInformation)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceInformation, battery) < 256 && pb_membersize(DeviceInformation, status) < 256 && pb_membersize(NotifyDeviceConfiguration, device_configuration) < 256 && pb_membersize(NotifyDeviceInformation, device_information) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_DeviceBattery_DeviceStatus_DeviceInformation_GetDeviceInformation_DeviceConfiguration_GetDeviceConfiguration_OverrideAssistant_StartSetup_CompleteSetup_NotifyDeviceConfiguration_UpdateDeviceInformation_NotifyDeviceInformation)
#endif


/* @@protoc_insertion_point(eof) */
