/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#include "speech.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Dialog_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Dialog, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t SpeechSettings_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, SpeechSettings, audio_profile, audio_profile, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, SpeechSettings, audio_format, audio_profile, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, SpeechSettings, audio_source, audio_format, 0),
    PB_LAST_FIELD
};

const pb_field_t SpeechInitiator_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, SpeechInitiator, type, type, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, SpeechInitiator, wake_word, type, &SpeechInitiator_WakeWord_fields),
    PB_LAST_FIELD
};

const pb_field_t SpeechInitiator_WakeWord_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, SpeechInitiator_WakeWord, start_index_in_samples, start_index_in_samples, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, SpeechInitiator_WakeWord, end_index_in_samples, start_index_in_samples, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, SpeechInitiator_WakeWord, near_miss, end_index_in_samples, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, STATIC  , OTHER, SpeechInitiator_WakeWord, metadata, near_miss, 0),
    PB_LAST_FIELD
};

const pb_field_t StartSpeech_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, StartSpeech, settings, settings, &SpeechSettings_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, StartSpeech, initiator, settings, &SpeechInitiator_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, StartSpeech, dialog, initiator, &Dialog_fields),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, StartSpeech, suppressEarcon, dialog, 0),
    PB_LAST_FIELD
};

const pb_field_t SpeechProvider_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, SpeechProvider, speech_settings, speech_settings, &SpeechSettings_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, SpeechProvider, dialog, speech_settings, &Dialog_fields),
    PB_LAST_FIELD
};

const pb_field_t ProvideSpeech_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ProvideSpeech, dialog, dialog, &Dialog_fields),
    PB_LAST_FIELD
};

const pb_field_t StopSpeech_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, StopSpeech, error_code, error_code, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, StopSpeech, dialog, error_code, &Dialog_fields),
    PB_LAST_FIELD
};

const pb_field_t EndpointSpeech_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, EndpointSpeech, dialog, dialog, &Dialog_fields),
    PB_LAST_FIELD
};

const pb_field_t NotifySpeechState_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, NotifySpeechState, state, state, 0),
    PB_LAST_FIELD
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SpeechInitiator, wake_word) < 65536 && pb_membersize(SpeechInitiator_WakeWord, metadata) < 65536 && pb_membersize(StartSpeech, settings) < 65536 && pb_membersize(StartSpeech, initiator) < 65536 && pb_membersize(StartSpeech, dialog) < 65536 && pb_membersize(SpeechProvider, speech_settings) < 65536 && pb_membersize(SpeechProvider, dialog) < 65536 && pb_membersize(ProvideSpeech, dialog) < 65536 && pb_membersize(StopSpeech, dialog) < 65536 && pb_membersize(EndpointSpeech, dialog) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Dialog_SpeechSettings_SpeechInitiator_SpeechInitiator_WakeWord_StartSpeech_SpeechProvider_ProvideSpeech_StopSpeech_EndpointSpeech_NotifySpeechState)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for SpeechInitiator_WakeWord.metadata is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
