/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#include "state.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t State_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, State, feature, feature, 0),
    PB_ONEOF_FIELD(value,   2, BOOL    , ONEOF, STATIC  , OTHER, State, boolean, feature, 0),
    PB_ONEOF_FIELD(value,   3, UINT32  , ONEOF, STATIC  , UNION, State, integer, feature, 0),
    PB_LAST_FIELD
};

const pb_field_t GetState_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, GetState, feature, feature, 0),
    PB_LAST_FIELD
};

const pb_field_t SetState_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, SetState, state, state, &State_fields),
    PB_LAST_FIELD
};

const pb_field_t SynchronizeState_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, SynchronizeState, state, state, &State_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SetState, state) < 65536 && pb_membersize(SynchronizeState, state) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_State_GetState_SetState_SynchronizeState)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SetState, state) < 256 && pb_membersize(SynchronizeState, state) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_State_GetState_SetState_SynchronizeState)
#endif


/* @@protoc_insertion_point(eof) */
