/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#include "system.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ResetConnection_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ResetConnection, timeout, timeout, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ResetConnection, force_disconnect, timeout, 0),
    PB_LAST_FIELD
};

const pb_field_t SynchronizeSettings_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, SynchronizeSettings, timestamp_hi, timestamp_hi, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, SynchronizeSettings, timestamp_lo, timestamp_hi, 0),
    PB_LAST_FIELD
};

const pb_field_t KeepAlive_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t RemoveDevice_fields[1] = {
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
