/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Nov 09 16:58:28 2018. */

#include "transport.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConnectionDetails_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, ConnectionDetails, identifier, identifier, 0),
    PB_LAST_FIELD
};

const pb_field_t UpgradeTransport_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, UpgradeTransport, transport, transport, 0),
    PB_LAST_FIELD
};

const pb_field_t SwitchTransport_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, SwitchTransport, new_transport, new_transport, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
